stages:
  - test

api_test:
  stage: test
  image: node:18
  before_script:
    - cd test_server
    - npm install
    - nohup npm start &
  script:
    - cd ../
    - npm run test
  only:
    - main
