name: API Testing Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install server dependencies
      run: |
        cd test_server
        npm install
    - name: Start test server
      run: |
        cd test_server
        nohup npm start &
    - name: Install test dependencies
      run: |
        cd ../
        npm install
    - name: Run tests
      run:
        npm run test
        
